language: node_js
node_js:
  - "10.12.0"
cache:
  directories:
  - node_modules
script:
  - CI=false npm run build
after_success:
  - npm install -g firebase-tools
  - cd functions && npm install
  - cd .. && firebase deploy --token $FIREBASE_TOKEN --non-interactive